services:
  jump-app:
    build: .
    container_name: jump-app
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:8.4
    container_name: jump-mysql
    restart: unless-stopped
    network_mode: host

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: jump
      MYSQL_USER: jump
      MYSQL_PASSWORD: jump123
      TZ: Asia/Shanghai

    volumes:
      - mysql_data:/var/lib/mysql

    command:
      - --port=3307
      - --mysqlx-port=33061
      - --bind-address=127.0.0.1
      - --mysqlx-bind-address=127.0.0.1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=300
      - --thread_cache_size=50
      - --table_open_cache=4096
      - --table_definition_cache=2048
      - --innodb_buffer_pool_size=1G
      - --innodb_buffer_pool_instances=1
      - --innodb_log_buffer_size=64M
      - --tmp_table_size=64M
      - --max_heap_table_size=64M
      - --innodb_flush_log_at_trx_commit=1
      - --sync_binlog=1

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-P",
          "3307",
          "-ujump",
          "-pjump123"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s


  redis:
    image: redis:7-alpine
    container_name: jump-redis
    restart: unless-stopped
    network_mode: host

    volumes:
      - redis_data:/data

    command:
      - redis-server
      - --bind
      - 127.0.0.1
      - ::1
      - --port
      - "6378"
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --save
      - "900 1"
      - --save
      - "300 10"
      - --save
      - "60 10000"
      - --maxmemory-policy
      - allkeys-lru

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "127.0.0.1",
          "-p",
          "6378",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s



volumes:
  mysql_data:
  redis_data: